name: CommandBlocker
version: '${project.version}'
main: me.jayie.commandblocker.CommandBlocker
api-version: 1.18
authors: [ Jayiewayie ]
description: Block commands and words
commands:
  cmdblocker:
    description: The base command for the plugin.
    aliases: [cmdb]
